/** Design tokens shared by the CRM and the Sales Screen. */
export const tokens = {
  color: {
    brand: 'var(--brand)',
    brandSoft: 'var(--brand-soft)',
    accent: 'var(--accent)',
    surface: 'var(--surface)',
    surfaceRaised: 'var(--surface-raised)',
    border: 'var(--border)',
    text: 'var(--text)',
    textMuted: 'var(--text-muted)',
    success: '#0f7b46',
    warning: '#b45309',
    danger: '#b42318',
    info: '#175cd3',
  },
  radius: { sm: '6px', md: '10px', lg: '16px', pill: '999px' },
  shadow: {
    sm: '0 1px 2px rgba(16,24,40,.06)',
    md: '0 4px 16px rgba(16,24,40,.08)',
    lg: '0 16px 48px rgba(16,24,40,.14)',
  },
};

export const STATUS_TONES = {
  draft: 'neutral',
  internal_review: 'info',
  approved: 'success',
  publishing: 'info',
  published: 'success',
  partially_published: 'warning',
  rejected: 'danger',
  unpublished: 'neutral',
  expired: 'warning',
  withdrawn: 'neutral',
  archived: 'neutral',
  available: 'success',
  on_hold: 'warning',
  reserved: 'info',
  booked: 'info',
  sold: 'success',
  blocked: 'danger',
  cancelled: 'danger',
  unreleased: 'neutral',
  unavailable: 'neutral',
  open: 'info',
  won: 'success',
  lost: 'danger',
  junk: 'neutral',
  pending: 'warning',
  failed: 'danger',
  healthy: 'success',
  degraded: 'warning',
  error: 'danger',
  unknown: 'neutral',
};
